language: python
python:
  - "3.5"

install: 
 - pip install beautifulsoup4
 - pip install codecov
script: python collect_tagalog.py

after_success:
  - codecov
  #- pip install coverage
  #- coverage run tests.py
  #- bash <(curl -s https://codecov.io/bash)
